# Generated by Django 2.1.7 on 2019-03-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
