# Generated by Django 2.1.5 on 2019-03-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='img_url',
            field=models.CharField(default='static/images/test.jpeg', max_length=200),
        ),
    ]
