# Generated by Django 2.1.5 on 2019-03-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190319_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='set',
            name='is_public',
        ),
    ]
