# Generated by Django 2.1.5 on 2019-03-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_set_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='img_url',
            new_name='image_url',
        ),
    ]
