# Generated by Django 2.1.5 on 2019-03-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_set_user'),
        ('main_app', '0003_auto_20190316_1810'),
    ]

    operations = [
    ]
